### ISSUE TITLE
from-scratch rewriting

### ISSUE THREAD

**Issue by atoy40** [aruntk/polymer-apollo#12]
hello, @aruntk 
Just to tell you I've reimplemented some ideas from scratch, because i've some difficulties to update your code (not easy to add a new functionnality without breaking an old one)
It's here, take a look and tell me :
https://github.com/atoy40/kapton

It's a very early publishing. It's inspired by the react-apollo package. In term of main functionnality, I've to add subscriptions, but nothing difficult.

Anthony.

**Comment by aruntk** [comment]
@atoy40  I'm currently rewriting the code. Felt the same issue.

**Comment by aruntk** [comment]
Btw I've implemented subscriptions, pagination and fetchMore.

**Comment by atoy40** [comment]
Yes I've seen your commits, but it looks to me more complicated that it can be :) i was suprised how small is my actual code ... to do all of that (subscription will be added with 2/3 more lines, no more). The main issue to me is the "apollo" configuration key that is not really integrated with polymer.
I'm writing a small demo application, I'll tell you when it'll be online.

**Comment by aruntk** [comment]
Okay. :)

**Comment by aruntk** [comment]
@atoy40 I rewrote the package from scratch including ideas from your implementation. Please check.

**Comment by atoy40** [comment]
@aruntk Ok, I'll check your new version today. On my side, I've coded a small sample using my idea. https://github.com/atoy40/kapton-sample

It's 100% client-side (graphql schema/endpoint embedded into the app through webpack) so I can have an instance "running" on github.
https://atoy40.github.io/kapton-sample/

**Comment by aruntk** [comment]
@atoy40 Okay. 👍 Example works great.
